# Cloudflare Workers configuration
name = "m3u8-proxy"
main = "dist/worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
# You can add any environment variables here if needed

# Build configuration
[build]
command = "npm run build"

# Development configuration
[env.development]
vars = { NODE_ENV = "development" }

# Production configuration  
[env.production]
vars = { NODE_ENV = "production", WORKER_ENV = "production" }

# Optional: Custom domains (uncomment and configure as needed)
# [[routes]]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"
